<a href="https://colab.research.google.com/github/dipa-khadka/Datacience_Class/blob/main/NumpyDS600_D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy :
     It is the fundamental package for scientifiic computing with Python.

In [ ]:
# installing Numpy
!pip install numpy

In [6]:
# importing numpy
import numpy as np # While importing numpy we shorten the imported name to np for better readability of code using Numpy.


In [7]:
# checking the version of numpy
np.__version__

'1.23.5'

In [8]:
# class work 1:
    # creating array of even number
even = [2, 44, 4, 8, 2, 6, 18]
type(even)

list

In [9]:
# converting even numbers into list to array
even_array = np.array(even)

In [10]:
even_array

array([ 2, 44,  4,  8,  2,  6, 18])

In [11]:
len(even_array)

7

In [12]:
type(even_array) #ndarray means n-dimensional array

numpy.ndarray

In [13]:
even_array.ndim # 'ndim' shows the number of dimension


1

In [14]:
even_array.shape

(7,)

class work

In [15]:
odd = [11,3,5,7,9,11]
type(odd)

list

In [16]:
# converting list to array
odd_array = np.array(odd)

In [17]:
odd_array

array([11,  3,  5,  7,  9, 11])

In [18]:
type(odd_array)

numpy.ndarray

In [19]:
odd_array.shape

(6,)

# Random Number generation using numpy


In [20]:
np.random.randint(1,100,)  # generate the random number between 1 to 100

96

In [21]:
np.random.seed(2023)
np.random.randint(1,100) # deterministic pseudorandom number generation

88

In [22]:
np.random.seed(8)
x = np.random.randint(low=1, high=100, size=8)
x

array([68, 85,  6, 91,  9, 84, 64, 49])

# Indexing and Slicing

In [23]:
# indexing
x[0]

68

In [24]:
# negative indexing
x[-1]

49

In [25]:
# slicing
x[0:4]

array([68, 85,  6, 91])

In [26]:
x[2:6]

array([ 6, 91,  9, 84])

In [27]:
x[::2]

array([68,  6,  9, 64])

In [28]:
x[-3:]

array([84, 64, 49])

In [29]:
x[0:5:1]

array([68, 85,  6, 91,  9])

# Difference between list and numpy
   
   * Numpy Array are memory efficient than python list.
   * Numpy Array are faster than python list
   * Numpy Array suppoets homogenous data type while python list supports multiple data type.

In [36]:
# Numpy Array are more memory efficient than python list.(example of this point):
python_list = [0, 0.25, 0.5, 0.75, 1] # By default list contain 64-bit memory space
python_list
type(python_list)

list

In [39]:
# converting python_list to Array
python_list_array = np.array(python_list)
type(python_list_array )
python_list_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [40]:
# checking the memory bit
python_list_array.dtype

dtype('float64')

In [44]:
# by using numpy array we can spacify the memory sapce so our memory won't be waste that's why numpy array are memory efficient
np.array(python_list, dtype=np.float16) #here i am spacifying memory of this data from 64  to 16

array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float16)

In [45]:
np.ones(shape=5, dtype=np.int8)

array([1, 1, 1, 1, 1], dtype=int8)

In [46]:
np.zeros(shape=2, dtype=np.float16)

array([0., 0.], dtype=float16)

* Numpy Array are faster than python list


In [47]:
np.random.seed(0)
x_array = np.random.randint(low=1, high=100, size=10000)
x_array

array([45, 48, 65, ..., 38, 26, 46])

In [49]:
# type casting (converting x_array to python_list)
x_list = x_array.tolist()
type(x_list)


list

In [50]:
# To find out the how many time consume to the shell
%%time #its called magic method
sq = [item**2 for item in x_list]

CPU times: user 3.17 ms, sys: 1.01 ms, total: 4.18 ms
Wall time: 4.18 ms


In [52]:
%%time
sq = [item**2 for item in x_array]

CPU times: user 2.85 ms, sys: 0 ns, total: 2.85 ms
Wall time: 2.86 ms


* Numpy Array supports homogineous datatypes while python lists supports multiple datatypes

In [53]:
# In pyhthon list
x = [True, 0, 55.3, 'hello']
type(x)

list

In [54]:
type(x[0])

bool

In [55]:
type(x[1])

int

In [56]:
type(x[2])

float

In [57]:
type(x[3])

str

In [59]:
# In Numpy Array
x_array = np.array(x) # conveting x to array
x_array

array(['True', '0', '55.3', 'hello'], dtype='<U32')

In [60]:
type(x_array[0]), type(x_array[1]), type(x_array[2]), type(x_array[3])

(numpy.str_, numpy.str_, numpy.str_, numpy.str_)

# .arange():
      The '.arange()' function work same as range in list(python). in Numpy we used .arange() instead of range().

In [63]:
x = np.arange(1,10, 1)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
list(range(1,10,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Linear Spacing

In [67]:
np.linspace(0,1,5) # It generates the 5 numbers between 0 to 1 with equal width

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [69]:
np.linspace(0,10,5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])