# sort and concat

In [1]:
import numpy as np

* Sort :
    To make in order of onordered list/data.

In [2]:
x = np.array([9, 0.2, -1, 0, -7, 6, 4, -5])

In [3]:
np.sort(x) # acending order

array([-7. , -5. , -1. ,  0. ,  0.2,  4. ,  6. ,  9. ])

In [6]:
np.flip(np.sort(x)) # descending order; if you flip ascending order it becomes descending

array([ 9. ,  6. ,  4. ,  0.2,  0. , -1. , -5. , -7. ])

* Concat

In [ ]:
# in list
a = [4, 8]
b= [3, 6, 9]
a + b # list concat

[4, 8, 3, 6, 9]

In [ ]:
# in array
a = np.array([4, 8])
b =np.array([3, 6, 9])

In [ ]:
# a + b  "+ operator le concatinae hudaina array ma"

In [ ]:
np.concatenate([a,b])

array([4, 8, 3, 6, 9])

# vector operation and broadcasting

* vector operation:
        vector operations focus on element-wise operations between arrays of the same shape.

In [ ]:
x = np.array([8, 4, 2])
y = np.array([2, 4, 2])
x + y

array([10,  8,  4])

In [ ]:
x - y

array([6, 0, 0])

In [ ]:
x / y

array([4., 1., 1.])

In [ ]:
x * y

array([16, 16,  4])

In [ ]:
x ** y

array([ 64, 256,   4])

* vector broadcasting:
         Vector broadcasting is a feature in Numpy that allows you to perform operations between arrays of different shape. It allows you to perform operations betweenarrays of diffrent shpaes by automatically adjusting the dimensions of the smaller array to make the operation valid.

In [ ]:
a = np.array([8,9,6,1]) # vector broadcasting is used in brigthness

In [ ]:
2 * a

array([16, 18, 12,  2])

In [ ]:
3 + a

array([11, 12,  9,  4])

In [7]:
# lets operate the operation between different shapes array
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])          #Broadcasting: b is automatically expanded to match the shape of a
c= a+b
c

array([[11, 22, 33],
       [14, 25, 36]])

# Statistics using Numpy

In [ ]:
np.random.seed(0)
data=np.random.randint(1,50,5)
data

array([45, 48,  1,  4,  4])

In [ ]:
# to calculate the mean of data
np.mean(data)

20.4

In [ ]:
# to calculate median
np.median(data)

4.0

In [ ]:
# to calculate mode we need to import scipy
from scipy.stats import mode
mode(data) # mode 4 ho and frequency or count 2 ho

In [ ]:
# to calculate standard deviation
np.std(data)

21.35977527971678

In [ ]:
# to calculate variance
np.var(data)

456.23999999999995

In [ ]:
# to calculate minimum value
np.min(data)

1

In [ ]:
# to caltulate maximum value
np.max(data)

48

In [ ]:
# to  calculate range
range = np.max(data) - np.min(data)
range

47

In [ ]:
# to find out the index of 48 (maximum value)
np.argmax(data) # arg tapepaxi chahin index herna mixa

1

In [ ]:
# to find out the index of 1 (minimum value)
np.argmin(data)

2

# .any() vs .all()

In [ ]:
height = np.array([1,2,3,4,5,6,6,5,4,3,2,1])

In [ ]:
height>=5 # this condition is boradcast

array([False, False, False, False,  True,  True,  True,  True, False,
       False, False, False])

In [ ]:
np.any(height>=5) # is there any person with hieght >= 5 ?

True

In [ ]:
np.all(height>=5)

False

In [ ]:
np.all(height>=1)

True

In [ ]:
height[height>=5] # to find out exact number of person with 5 foot height

array([5, 6, 6, 5])

In [ ]:
# to find out greater than 2 foot to less than 5 foot person
height[height <2 and height > 5 ] # numpy array doesn't acept logical operator

In [ ]:
# instead of use bitwise operator
[(height<3) & (height>5)] # bitwise operator and (&) ko side ko condition haru () backet vitra lekhnu parxa

[array([False, False, False, False, False, False, False, False, False,
        False, False, False])]

In [ ]:
height[(height > 3) & (height < 5)]

array([4, 4])

# Two dimensional array

In [3]:
data = [ [1,2,3], [4,5,6], [7,8,9]] # it is list of list

In [4]:
# converting to array
matrix = np.array(data)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# to find shape
matrix.shape # (no of rows and no of columns)

(3, 3)

In [ ]:
# to find out no of dimension

matrix.ndim

2

In [ ]:
matrix [0,1]

2

In [ ]:
matrix [2,2]

9

In [ ]:
matrix[1,2]

6

In [ ]:
matrix [1, :] # slicing

array([4, 5, 6])

In [ ]:
matrix [2, :]

array([7, 8, 9])

In [ ]:
matrix [ :, 2]

array([3, 6, 9])

In [ ]:
matrix [ : , 0]

array([1, 4, 7])

In [ ]:
matrix [:, 1]

array([2, 5, 8])

In [ ]:
# to find out 5,6,8,9
matrix[1 : , 1 :]

array([[5, 6],
       [8, 9]])

In [ ]:
matrix[1: , :2]

array([[4, 5],
       [7, 8]])

In [5]:
matrix[:2,:2]

array([[1, 2],
       [4, 5]])

In [6]:
# here we going to operate between 5*5 matrix
x_matrix=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
x_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
x_matrix.ndim


2

In [8]:
# to find out (11,12,13,14,15,16,17,18,19,20)
x_matrix[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
# to find out (1,2,,6,7):
x_matrix[:2,:2] 

array([[1, 2],
       [6, 7]])

In [11]:
# to find out (11,12,16,17)
x_matrix[2:4,:2]

array([[11, 12],
       [16, 17]])

In [12]:
# to find out(18,19,23,24)
x_matrix[2:4,:2]

array([[11, 12],
       [16, 17]])

In [13]:
# to find out (1,2,3,4,5)
x_matrix[:1:2]

array([[1, 2, 3, 4, 5]])

In [15]:
# to find out (6,7,8,9,10)
x_matrix[1:2]

array([[ 6,  7,  8,  9, 10]])

In [16]:
# to find out (16,17,18,19,20)
x_matrix[3:4]

array([[16, 17, 18, 19, 20]])

In [17]:
# to fiind out (21,22,23,24,25)
x_matrix[4:]

array([[21, 22, 23, 24, 25]])

In [18]:
# to find out(11,12,13,14,15)
x_matrix[2:3]

array([[11, 12, 13, 14, 15]])

In [19]:
# to find out (14,15,19,20)
x_matrix[2:4,3:]

array([[14, 15],
       [19, 20]])

In [20]:
# to find out (7,8,9,12,13,14)
x_matrix[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])