In [ ]:
import numpy as np


# Matrix multiplication or dot product

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])

In [ ]:
A.shape   # let m*n

(2, 3)

In [ ]:
B.shape  # let p*q

(3, 2)

In [ ]:
# if n==p vay vane matrix multiply hunxa

In [ ]:
output=np.dot(A,B)
output

array([[ 58,  64],
       [139, 154]])

# Determinant Transpose and inverse of Matrix

In [ ]:
# Transpose (row  column hunxa and column row hunxa transpose ma)
output.T

array([[ 58, 139],
       [ 64, 154]])

In [ ]:
# to find out determination
det=np.linalg.det(output)
det

36.000000000000256

In [ ]:
np.round(det)

36.0

In [ ]:
# to calculalte inverse
np.linalg.inv(output)


array([[ 4.27777778, -1.77777778],
       [-3.86111111,  1.61111111]])

# The axis argument in numpy: 2D axis=0 is column-wise and axis=1 means row-wise

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# we want total sum of each item in an array
x.sum(x)

21

In [ ]:
# vertically sum
x.sum(axis=0)

array([5, 7, 9])

In [ ]:
# horizontally sum
x.sum(axis=1)

array([ 6, 15])

In [ ]:
# to find out veertically mean
x.mean(axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
# To find out horizontally mean
x.mean(axis=1)

array([2., 5.])

# .reshape():
  To change/convert one dimension to another dimension. it is used to change the shape.

In [ ]:
x=np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [ ]:
x.shape

(6,)

In [ ]:
x.ndim

1

In [ ]:
# to convert x to matrix
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
x.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

# Row matrix and Column matrix:
<img src="https://d20khd7ddkh5ls.cloudfront.net/row_column_matrices.jpg">

In [ ]:
x=np.array([8,2,0,3,5,9])

In [ ]:
# Row matrix: in this number of row 1 hunxa and comumn unkown hunxa. unkown lai =1 le represent garne
x.reshape(1, -1)

array([[8, 2, 0, 3, 5, 9]])

In [ ]:
# column matrix : number of row unkown hunxa and column 1 hunxa . unkown lai chahi -1 le represent garinxa
x.reshape(-1,1)

array([[8],
       [2],
       [0],
       [3],
       [5],
       [9]])

# Converting 2D array to 1D

In [ ]:
matrix= np.array([[2,6],[8,9]])
matrix

array([[2, 6],
       [8, 9]])

In [ ]:
# code to converting 2d to 1d
flat_array = matrix.flatten() # deep learning and data cleaning ma use hunxa flatten
flat_array

array([2, 6, 8, 9])

In [ ]:
flat_array.ndim

1

In [ ]:
# to convert array into python list
flat_array.tolist()

[2, 6, 8, 9]

# Morden day images are in 3D:
`
(row,column,channel)`

In [ ]:
np.zeros((2,3,4)) # simply means 2 sets 3 rows per set 3 colums

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.random.rand(3,4,5)

array([[[2.41640104e-01, 8.63358819e-01, 5.86592042e-01, 5.09138579e-01,
         7.26187632e-01],
        [5.66765235e-01, 7.83635046e-01, 4.57058912e-02, 5.29841654e-01,
         6.81998668e-01],
        [3.38514640e-01, 5.13304623e-01, 2.09138942e-01, 3.83381287e-01,
         6.97976826e-01],
        [2.96612686e-01, 8.56060767e-01, 3.90711755e-02, 7.90055354e-01,
         6.26183019e-01]],

       [[4.67872730e-01, 5.71094526e-02, 7.16731747e-01, 1.19165285e-01,
         9.97071555e-01],
        [5.46604106e-01, 5.82143489e-01, 1.25566585e-01, 2.02183169e-01,
         9.11616533e-01],
        [2.25426136e-01, 3.94857279e-01, 5.17411074e-01, 2.45237402e-01,
         5.38893373e-01],
        [3.04421223e-01, 5.84882620e-01, 7.06885407e-05, 6.57869350e-01,
         7.21679999e-01]],

       [[6.41016649e-01, 9.03143223e-01, 7.55657970e-01, 8.53833303e-01,
         7.62829885e-01],
        [4.13613885e-01, 7.35251779e-01, 4.63614331e-01, 4.00560768e-01,
         2.74768051e-01],
      

In [ ]:
# in 1D:


In [ ]:
#